const AUTO_ID_PATTERNS = [
  /^:r[a-z0-9]+:$/,
  /^react-/,
  /^__next/,
  /^radix-/,
  /^headlessui-/,
  /^rc-/,
  /^[a-f0-9]{8,}$/,
  /^\d+$/,
];

const GENERATED_CLASS_PATTERNS = [
  /^css-[a-z0-9]+$/,
  /^sc-[a-zA-Z]{6,}$/,
  /^_[a-zA-Z0-9]{5,}_[a-z0-9]+$/,
  /^svelte-[a-z0-9]+$/,
  /^[a-z]{20,}$/,
];

function isAutoGeneratedId(id: string): boolean {
  return AUTO_ID_PATTERNS.some((p) => p.test(id));
}

function isGeneratedClass(cls: string): boolean {
  return GENERATED_CLASS_PATTERNS.some((p) => p.test(cls));
}

function isTailwindUtility(cls: string): boolean {
  const prefixes = [
    "flex", "grid", "block", "inline", "hidden", "relative", "absolute",
    "fixed", "sticky", "top-", "bottom-", "left-", "right-", "inset-",
    "z-", "w-", "h-", "min-", "max-", "p-", "px-", "py-", "pt-", "pb-",
    "pl-", "pr-", "m-", "mx-", "my-", "mt-", "mb-", "ml-", "mr-", "gap-",
    "space-", "text-", "font-", "leading-", "tracking-", "bg-", "border",
    "rounded", "shadow", "opacity-", "transition", "duration-", "ease-",
    "cursor-", "overflow-", "items-", "justify-", "self-", "col-", "row-",
    "object-", "hover:", "focus:", "active:", "dark:", "sm:", "md:", "lg:",
    "xl:", "2xl:", "group", "peer",
  ];
  return prefixes.some((p) => cls.startsWith(p));
}

function escapeSelector(str: string): string {
  return CSS.escape(str);
}

function validate(selector: string, target: HTMLElement): boolean {
  try {
    const matches = document.querySelectorAll(selector);
    return matches.length === 1 && matches[0] === target;
  } catch {
    return false;
  }
}

function tryIdSelector(el: HTMLElement): string | null {
  if (!el.id || isAutoGeneratedId(el.id)) return null;
  const sel = `#${escapeSelector(el.id)}`;
  return validate(sel, el) ? sel : null;
}

function tryTestIdSelector(el: HTMLElement): string | null {
  const attrs = ["data-testid", "data-cy", "data-test"];
  for (const attr of attrs) {
    const val = el.getAttribute(attr);
    if (val) {
      const sel = `[${attr}="${escapeSelector(val)}"]`;
      if (validate(sel, el)) return sel;
    }
  }
  return null;
}

function trySemanticSelector(el: HTMLElement): string | null {
  const tag = el.tagName.toLowerCase();

  const role = el.getAttribute("role");
  if (role) {
    const sel = `${tag}[role="${escapeSelector(role)}"]`;
    if (validate(sel, el)) return sel;
  }

  const ariaLabel = el.getAttribute("aria-label");
  if (ariaLabel) {
    const sel = `${tag}[aria-label="${escapeSelector(ariaLabel)}"]`;
    if (validate(sel, el)) return sel;
  }

  if (tag === "a") {
    const href = el.getAttribute("href");
    if (href && href !== "#") {
      const sel = `a[href="${escapeSelector(href)}"]`;
      if (validate(sel, el)) return sel;
    }
  }

  if (tag === "input" || tag === "textarea" || tag === "select") {
    const name = el.getAttribute("name");
    if (name) {
      const sel = `${tag}[name="${escapeSelector(name)}"]`;
      if (validate(sel, el)) return sel;
    }
    const placeholder = el.getAttribute("placeholder");
    if (placeholder) {
      const sel = `${tag}[placeholder="${escapeSelector(placeholder)}"]`;
      if (validate(sel, el)) return sel;
    }
  }

  return null;
}

function tryClassSelector(el: HTMLElement): string | null {
  const classes = Array.from(el.classList).filter(
    (c) => !isGeneratedClass(c) && !isTailwindUtility(c) && c.length > 1
  );
  if (classes.length === 0) return null;

  const tag = el.tagName.toLowerCase();

  for (const cls of classes) {
    const sel = `${tag}.${escapeSelector(cls)}`;
    if (validate(sel, el)) return sel;
  }

  for (let i = 0; i < classes.length; i++) {
    for (let j = i + 1; j < classes.length; j++) {
      const sel = `${tag}.${escapeSelector(classes[i])}.${escapeSelector(classes[j])}`;
      if (validate(sel, el)) return sel;
    }
  }

  for (const cls of classes) {
    const sel = `.${escapeSelector(cls)}`;
    if (validate(sel, el)) return sel;
  }

  return null;
}

function getNthChildPath(el: HTMLElement): string {
  const parts: string[] = [];
  let current: HTMLElement | null = el;

  while (current && current !== document.documentElement) {
    const tag = current.tagName.toLowerCase();
    const parent: HTMLElement | null = current.parentElement;

    if (parent) {
      const siblings = Array.from(parent.children).filter(
        (s: Element) => s.tagName.toLowerCase() === tag
      );
      if (siblings.length > 1) {
        const index = Array.from(parent.children).filter((s: Element) => s.tagName.toLowerCase() === tag).indexOf(current) + 1;
        parts.unshift(`${tag}:nth-of-type(${index})`);
      } else {
        parts.unshift(tag);
      }
    } else {
      parts.unshift(tag);
    }

    if (current.id && !isAutoGeneratedId(current.id)) {
      parts[0] = `#${escapeSelector(current.id)} > ${parts[0]}`;
      break;
    }

    const testId = current.getAttribute("data-testid");
    if (testId) {
      parts[0] = `[data-testid="${escapeSelector(testId)}"] > ${parts[0]}`;
      break;
    }

    current = parent;
  }

  return parts.join(" > ");
}

export function generateSelector(el: HTMLElement): string {
  const result =
    tryIdSelector(el) ??
    tryTestIdSelector(el) ??
    trySemanticSelector(el) ??
    tryClassSelector(el) ??
    getNthChildPath(el);

  if (validate(result, el)) return result;

  return getNthChildPath(el);
}
